services:
  webapp:
    build:
      context: ../webapp/rust
      dockerfile: ../../development/dockerfiles/Dockerfile.rust
    volumes:
      - ../webapp/sql:/home/isucon/webapp/sql:ro
    environment:
      ISUCON_DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
  matcher:
    command: /bin/sh -c "while true; do curl -s http://nginx/api/internal/matching; sleep 0.5; done"
    depends_on:
      - nginx
  nginx:
    image: nginx:1.28-alpine
    ports:
      - "8080:80"
    volumes:
      - ./profiling/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
